import Link from "next/link";
import { getMyClassActivity } from "@/lib/xp/server";
import { attendanceLabels, formatSessionDate } from "@/lib/classes/format";

export async function MyClassActivity() {
  const activity = await getMyClassActivity();
  const earned = activity.total_xp - activity.level_start_xp;
  const required = activity.next_level_xp - activity.level_start_xp;
  return <section className="mt-12 space-y-8 border-t border-border pt-8" aria-labelledby="my-class-activity-heading">
    <div><p className="text-xs font-semibold tracking-widest text-gold">YOUR CLASS RECORD</p><h2 id="my-class-activity-heading" className="mt-3 text-2xl font-semibold">내 출석과 활동</h2><p className="mt-3 text-sm leading-relaxed text-ink/70">레벨은 활동 기록이며 포커 실력이나 권한을 뜻하지 않습니다. 출석 정정으로 XP와 레벨이 조정될 수 있습니다.</p></div>
    <div className="rounded-card border border-border bg-glass p-6"><div className="flex flex-wrap items-baseline justify-between gap-3"><p className="text-2xl font-semibold text-gold">LEVEL {activity.level}</p><p className="font-mono text-sm">{activity.total_xp.toLocaleString("ko-KR")} XP</p></div><label htmlFor="activity-progress" className="mt-5 block text-sm text-ink/70">다음 레벨까지 {(activity.next_level_xp - activity.total_xp).toLocaleString("ko-KR")} XP</label><progress id="activity-progress" max={required} value={earned} className="mt-3 h-2 w-full accent-gold" /><p className="mt-3 text-xs leading-relaxed text-ink/70">완료·확정된 클래스 출석은 회차당 100 XP입니다.</p></div>
    <div><h3 className="text-lg font-semibold">최근 출석 · 최대 50회</h3>{!activity.attendance.length ? <p className="mt-4 text-sm text-ink/70">아직 시작된 회차의 출석 기록이 없습니다.</p> : <ol className="mt-4 divide-y divide-border">{activity.attendance.map(row => <li key={row.session_id} className="py-5"><div className="flex flex-wrap items-baseline justify-between gap-3"><Link href={`/class/${row.class_id}`} className="font-semibold underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-gold">{row.class_name} / {row.session_number}회차</Link><span className="text-sm text-gold">{row.cancelled_at ? "취소" : attendanceLabels[row.mark]}{!row.cancelled_at && !row.attendance_locked ? " · 확정 전" : ""}</span></div><p className="mt-2 text-sm text-ink/70">{formatSessionDate(row.scheduled_at)}</p></li>)}</ol>}</div>
    <details className="rounded-lg border border-border p-5"><summary className="cursor-pointer py-2 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-gold">XP 지급·조정 이력 · 최근 50건</summary>{!activity.ledger.length ? <p className="mt-4 text-sm text-ink/70">아직 지급·조정된 XP가 없습니다.</p> : <ol className="mt-4 divide-y divide-border">{activity.ledger.map(row => <li key={row.id} className="py-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-medium">{row.class_name} / {row.session_number}회차</p><p className="font-mono text-sm text-gold">{row.delta > 0 ? "+" : ""}{row.delta} XP</p></div><p className="mt-2 text-xs text-ink/70">{formatSessionDate(row.created_at)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-ink/70">{row.reason === "COMPLETE" ? "회차 완료 출석 지급" : row.reason === "LOCK" ? "출석 확정" : row.reason}</p></li>)}</ol>}</details>
  </section>;
}
